import React, { useState } from 'react';

const FORMATS = [
  { id: 'bicep', label: 'Bicep', icon: '💪', ext: '.bicep' },
  { id: 'powershell', label: 'PowerShell', icon: '⚡', ext: '.ps1' },
  { id: 'azcli', label: 'Azure CLI', icon: '🖥️', ext: '.sh' },
  { id: 'onprem', label: 'On-Prem DNS', icon: '🏢', ext: '.ps1' },
];

function generateBicep(config) {
  return `// ============================================================
// Hybrid DNS Architecture — Bicep Deployment
// Generated by Hybrid DNS Architect
// Docs: https://learn.microsoft.com/azure/dns/private-resolver-hybrid-dns
// ============================================================

targetScope = 'resourceGroup'

@description('Azure region for deployment')
param location string = '${config.location}'

@description('Name of the hub virtual network')
param vnetName string = '${config.azureVnetName}'

@description('CIDR for the hub virtual network')
param vnetAddressPrefix string = '${config.azureVnetCidr}'

@description('CIDR for the DNS resolver inbound subnet')
param inboundSubnetPrefix string = '${config.resolverSubnetCidr}'

@description('CIDR for the DNS resolver outbound subnet')
param outboundSubnetPrefix string = '${config.outboundSubnetCidr}'

@description('Name of the DNS Private Resolver')
param resolverName string = '${config.resolverName}'

@description('Name of the private DNS zone')
param privateZoneName string = '${config.privateZoneName}'

@description('IP of on-premises DNS server')
param onPremDnsIp string = '${config.onpremDnsIp}'

@description('On-premises domain name')
param onPremDomain string = '${config.onpremDomain}'

// ─── Virtual Network ──────────────────────────────────────
resource vnet 'Microsoft.Network/virtualNetworks@2023-11-01' = {
  name: vnetName
  location: location
  properties: {
    addressSpace: {
      addressPrefixes: [vnetAddressPrefix]
    }
    subnets: [
      {
        name: 'snet-dns-inbound'
        properties: {
          addressPrefix: inboundSubnetPrefix
          delegations: [
            {
              name: 'Microsoft.Network.dnsResolvers'
              properties: {
                serviceName: 'Microsoft.Network/dnsResolvers'
              }
            }
          ]
        }
      }
      {
        name: 'snet-dns-outbound'
        properties: {
          addressPrefix: outboundSubnetPrefix
          delegations: [
            {
              name: 'Microsoft.Network.dnsResolvers'
              properties: {
                serviceName: 'Microsoft.Network/dnsResolvers'
              }
            }
          ]
        }
      }
    ]
  }
}

// ─── DNS Private Resolver ─────────────────────────────────
resource dnsResolver 'Microsoft.Network/dnsResolvers@2022-07-01' = {
  name: resolverName
  location: location
  properties: {
    virtualNetwork: {
      id: vnet.id
    }
  }
}

// ─── Inbound Endpoint ─────────────────────────────────────
resource inboundEndpoint 'Microsoft.Network/dnsResolvers/inboundEndpoints@2022-07-01' = {
  parent: dnsResolver
  name: 'inbound-endpoint'
  location: location
  properties: {
    ipConfigurations: [
      {
        subnet: {
          id: vnet.properties.subnets[0].id
        }
        privateIpAllocationMethod: 'Dynamic'
      }
    ]
  }
}

// ─── Outbound Endpoint ────────────────────────────────────
resource outboundEndpoint 'Microsoft.Network/dnsResolvers/outboundEndpoints@2022-07-01' = {
  parent: dnsResolver
  name: 'outbound-endpoint'
  location: location
  properties: {
    subnet: {
      id: vnet.properties.subnets[1].id
    }
  }
}

// ─── DNS Forwarding Ruleset ───────────────────────────────
resource forwardingRuleset 'Microsoft.Network/dnsForwardingRulesets@2022-07-01' = {
  name: '\${resolverName}-ruleset'
  location: location
  properties: {
    dnsResolverOutboundEndpoints: [
      {
        id: outboundEndpoint.id
      }
    ]
  }
}

// ─── Forwarding Rule (On-Prem Domain) ─────────────────────
resource forwardingRule 'Microsoft.Network/dnsForwardingRulesets/forwardingRules@2022-07-01' = {
  parent: forwardingRuleset
  name: 'rule-onprem'
  properties: {
    domainName: '\${onPremDomain}.'
    targetDnsServers: [
      {
        ipAddress: onPremDnsIp
        port: 53
      }
    ]
    forwardingRuleState: 'Enabled'
  }
}

// ─── VNet Link to Forwarding Ruleset ──────────────────────
resource rulesetVnetLink 'Microsoft.Network/dnsForwardingRulesets/virtualNetworkLinks@2022-07-01' = {
  parent: forwardingRuleset
  name: '\${vnetName}-link'
  properties: {
    virtualNetwork: {
      id: vnet.id
    }
  }
}

// ─── Private DNS Zone ─────────────────────────────────────
resource privateDnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateZoneName
  location: 'global'
}

// ─── VNet Link to Private DNS Zone ────────────────────────
resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZone
  name: '\${vnetName}-link'
  location: 'global'
  properties: {
    virtualNetwork: {
      id: vnet.id
    }
    registrationEnabled: false
  }
}

// ─── Test Record ──────────────────────────────────────────
resource testRecord 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZone
  name: 'test'
  properties: {
    ttl: 3600
    aRecords: [
      {
        ipv4Address: '10.10.1.10'
      }
    ]
  }
}

// ─── Outputs ──────────────────────────────────────────────
output resolverInboundIp string = inboundEndpoint.properties.ipConfigurations[0].privateIpAddress
output privateZoneId string = privateDnsZone.id
output forwardingRulesetId string = forwardingRuleset.id
`;
}

function generatePowerShell(config) {
  return `# ============================================================
# Hybrid DNS Architecture — PowerShell Deployment
# Generated by Hybrid DNS Architect
# Docs: https://learn.microsoft.com/azure/dns/private-resolver-hybrid-dns
# ============================================================

# Variables
$resourceGroup = "${config.resourceGroup}"
$location = "${config.location}"
$vnetName = "${config.azureVnetName}"
$vnetCidr = "${config.azureVnetCidr}"
$inboundSubnetCidr = "${config.resolverSubnetCidr}"
$outboundSubnetCidr = "${config.outboundSubnetCidr}"
$resolverName = "${config.resolverName}"
$privateZoneName = "${config.privateZoneName}"
$onPremDnsIp = "${config.onpremDnsIp}"
$onPremDomain = "${config.onpremDomain}"

# Create Resource Group
New-AzResourceGroup -Name $resourceGroup -Location $location

# Create VNet with subnets
$inboundSubnet = New-AzVirtualNetworkSubnetConfig \`
    -Name "snet-dns-inbound" \`
    -AddressPrefix $inboundSubnetCidr \`
    -Delegation (New-AzDelegation -Name "dns" -ServiceName "Microsoft.Network/dnsResolvers")

$outboundSubnet = New-AzVirtualNetworkSubnetConfig \`
    -Name "snet-dns-outbound" \`
    -AddressPrefix $outboundSubnetCidr \`
    -Delegation (New-AzDelegation -Name "dns" -ServiceName "Microsoft.Network/dnsResolvers")

$vnet = New-AzVirtualNetwork \`
    -Name $vnetName \`
    -ResourceGroupName $resourceGroup \`
    -Location $location \`
    -AddressPrefix $vnetCidr \`
    -Subnet $inboundSubnet, $outboundSubnet

# Create DNS Private Resolver
$resolver = New-AzDnsResolver \`
    -Name $resolverName \`
    -ResourceGroupName $resourceGroup \`
    -Location $location \`
    -VirtualNetworkId $vnet.Id

# Create Inbound Endpoint
$inboundIpConfig = New-AzDnsResolverIPConfigurationObject \`
    -PrivateIPAllocationMethod "Dynamic" \`
    -SubnetId $vnet.Subnets[0].Id

$inboundEndpoint = New-AzDnsResolverInboundEndpoint \`
    -DnsResolverName $resolverName \`
    -Name "inbound-endpoint" \`
    -ResourceGroupName $resourceGroup \`
    -Location $location \`
    -IPConfiguration $inboundIpConfig

# Create Outbound Endpoint
$outboundEndpoint = New-AzDnsResolverOutboundEndpoint \`
    -DnsResolverName $resolverName \`
    -Name "outbound-endpoint" \`
    -ResourceGroupName $resourceGroup \`
    -Location $location \`
    -SubnetId $vnet.Subnets[1].Id

# Create Forwarding Ruleset
$ruleset = New-AzDnsForwardingRuleset \`
    -Name "$resolverName-ruleset" \`
    -ResourceGroupName $resourceGroup \`
    -Location $location \`
    -DnsResolverOutboundEndpoint @(@{Id = $outboundEndpoint.Id})

# Create Forwarding Rule
$targetDns = New-AzDnsForwardingRulesetTargetDnsServerObject \`
    -IPAddress $onPremDnsIp -Port 53

New-AzDnsForwardingRulesetForwardingRule \`
    -DnsForwardingRulesetName "$resolverName-ruleset" \`
    -Name "rule-onprem" \`
    -ResourceGroupName $resourceGroup \`
    -DomainName "$onPremDomain." \`
    -TargetDnsServer $targetDns \`
    -ForwardingRuleState "Enabled"

# Link VNet to Ruleset
New-AzDnsForwardingRulesetVirtualNetworkLink \`
    -DnsForwardingRulesetName "$resolverName-ruleset" \`
    -Name "$vnetName-link" \`
    -ResourceGroupName $resourceGroup \`
    -VirtualNetworkId $vnet.Id

# Create Private DNS Zone
$zone = New-AzPrivateDnsZone \`
    -Name $privateZoneName \`
    -ResourceGroupName $resourceGroup

# Link VNet to Private Zone
New-AzPrivateDnsVirtualNetworkLink \`
    -ZoneName $privateZoneName \`
    -Name "$vnetName-link" \`
    -ResourceGroupName $resourceGroup \`
    -VirtualNetworkId $vnet.Id

# Create test A record
New-AzPrivateDnsRecordSet \`
    -ZoneName $privateZoneName \`
    -ResourceGroupName $resourceGroup \`
    -Name "test" \`
    -RecordType A \`
    -Ttl 3600 \`
    -PrivateDnsRecord (New-AzPrivateDnsRecordConfig -IPv4Address "10.10.1.10")

# Output
Write-Host "Inbound Endpoint IP:" $inboundEndpoint.IPConfigurations[0].PrivateIPAddress
Write-Host "Configure on-prem conditional forwarder for '$privateZoneName' → above IP"
`;
}

function generateAzCli(config) {
  return `#!/bin/bash
# ============================================================
# Hybrid DNS Architecture — Azure CLI Deployment
# Generated by Hybrid DNS Architect
# Docs: https://learn.microsoft.com/azure/dns/private-resolver-hybrid-dns
# ============================================================

RG="${config.resourceGroup}"
LOCATION="${config.location}"
VNET="${config.azureVnetName}"
VNET_CIDR="${config.azureVnetCidr}"
INBOUND_CIDR="${config.resolverSubnetCidr}"
OUTBOUND_CIDR="${config.outboundSubnetCidr}"
RESOLVER="${config.resolverName}"
ZONE="${config.privateZoneName}"
ONPREM_DNS="${config.onpremDnsIp}"
ONPREM_DOMAIN="${config.onpremDomain}"

# Create Resource Group
az group create --name $RG --location $LOCATION

# Create VNet
az network vnet create \\
  --name $VNET \\
  --resource-group $RG \\
  --location $LOCATION \\
  --address-prefix $VNET_CIDR

# Create Inbound Subnet (delegated to DNS resolvers)
az network vnet subnet create \\
  --name snet-dns-inbound \\
  --vnet-name $VNET \\
  --resource-group $RG \\
  --address-prefix $INBOUND_CIDR \\
  --delegations "Microsoft.Network/dnsResolvers"

# Create Outbound Subnet (delegated to DNS resolvers)
az network vnet subnet create \\
  --name snet-dns-outbound \\
  --vnet-name $VNET \\
  --resource-group $RG \\
  --address-prefix $OUTBOUND_CIDR \\
  --delegations "Microsoft.Network/dnsResolvers"

# Create DNS Private Resolver
az dns-resolver create \\
  --name $RESOLVER \\
  --resource-group $RG \\
  --location $LOCATION \\
  --id "/subscriptions/\$(az account show --query id -o tsv)/resourceGroups/$RG/providers/Microsoft.Network/virtualNetworks/$VNET"

# Create Inbound Endpoint
INBOUND_SUBNET_ID=\$(az network vnet subnet show \\
  --name snet-dns-inbound --vnet-name $VNET --resource-group $RG \\
  --query id -o tsv)

az dns-resolver inbound-endpoint create \\
  --dns-resolver-name $RESOLVER \\
  --name inbound-endpoint \\
  --resource-group $RG \\
  --location $LOCATION \\
  --ip-configurations "[{private-ip-allocation-method:Dynamic,subnet:{id:$INBOUND_SUBNET_ID}}]"

# Create Outbound Endpoint
OUTBOUND_SUBNET_ID=\$(az network vnet subnet show \\
  --name snet-dns-outbound --vnet-name $VNET --resource-group $RG \\
  --query id -o tsv)

az dns-resolver outbound-endpoint create \\
  --dns-resolver-name $RESOLVER \\
  --name outbound-endpoint \\
  --resource-group $RG \\
  --location $LOCATION \\
  --id $OUTBOUND_SUBNET_ID

# Create Forwarding Ruleset
OUTBOUND_EP_ID=\$(az dns-resolver outbound-endpoint show \\
  --dns-resolver-name $RESOLVER --name outbound-endpoint \\
  --resource-group $RG --query id -o tsv)

az dns-resolver forwarding-ruleset create \\
  --name \${RESOLVER}-ruleset \\
  --resource-group $RG \\
  --location $LOCATION \\
  --outbound-endpoints "[{id:$OUTBOUND_EP_ID}]"

# Create Forwarding Rule
az dns-resolver forwarding-rule create \\
  --ruleset-name \${RESOLVER}-ruleset \\
  --name rule-onprem \\
  --resource-group $RG \\
  --domain-name "\${ONPREM_DOMAIN}." \\
  --target-dns-servers "[{ip-address:$ONPREM_DNS,port:53}]" \\
  --forwarding-rule-state Enabled

# Link VNet to Ruleset
VNET_ID=\$(az network vnet show --name $VNET --resource-group $RG --query id -o tsv)

az dns-resolver forwarding-ruleset vnet-link create \\
  --ruleset-name \${RESOLVER}-ruleset \\
  --name \${VNET}-link \\
  --resource-group $RG \\
  --id $VNET_ID

# Create Private DNS Zone
az network private-dns zone create \\
  --name $ZONE \\
  --resource-group $RG

# Link VNet to Private Zone
az network private-dns link vnet create \\
  --zone-name $ZONE \\
  --name \${VNET}-link \\
  --resource-group $RG \\
  --virtual-network $VNET_ID \\
  --registration-enabled false

# Create test record
az network private-dns record-set a add-record \\
  --zone-name $ZONE \\
  --resource-group $RG \\
  --record-set-name test \\
  --ipv4-address 10.10.1.10

# Get inbound endpoint IP
INBOUND_IP=\$(az dns-resolver inbound-endpoint show \\
  --dns-resolver-name $RESOLVER --name inbound-endpoint \\
  --resource-group $RG \\
  --query "ipConfigurations[0].privateIpAddress" -o tsv)

echo "============================================"
echo "Inbound Endpoint IP: $INBOUND_IP"
echo "Configure on-prem conditional forwarder:"
echo "  Zone: $ZONE → $INBOUND_IP"
echo "============================================"
`;
}

function generateOnPremDns(config) {
  return `# ============================================================
# On-Premises DNS Configuration — Windows DNS Server
# Generated by Hybrid DNS Architect
# Docs: https://learn.microsoft.com/azure/dns/private-resolver-hybrid-dns
# ============================================================
# Run these commands on your on-premises Windows DNS Server
# (typically a Domain Controller running DNS role)

# Step 1: Add Conditional Forwarder for Azure Private DNS Zone
# This tells your on-prem DNS to forward queries for 
# "${config.privateZoneName}" to the Azure DNS Private Resolver
# inbound endpoint.

Add-DnsServerConditionalForwarderZone \`
    -Name "${config.privateZoneName}" \`
    -MasterServers ${config.inboundEndpointIp} \`
    -ReplicationScope "Forest"

# Step 2: Verify the conditional forwarder was created
Get-DnsServerZone -Name "${config.privateZoneName}"

# Step 3: Test DNS resolution from on-premises
# This should resolve via: On-Prem DNS → ${config.connectionType === 'vpn' ? 'VPN' : 'ExpressRoute'} → Inbound Endpoint → Private Zone
Resolve-DnsName -Name "test.${config.privateZoneName}" -Server ${config.onpremDnsIp}

# ============================================================
# Verification from Azure side (run on Azure VM):
# nslookup testdns.${config.onpremDomain}
# This should resolve via: Azure DNS → Outbound Endpoint → 
# Forwarding Rule → ${config.connectionType === 'vpn' ? 'VPN' : 'ExpressRoute'} → On-Prem DNS (${config.onpremDnsIp})
# ============================================================

# Troubleshooting Commands:
# ─────────────────────────
# Check conditional forwarders
Get-DnsServerZone | Where-Object { $_.ZoneType -eq 'Forwarder' }

# Test forward lookup
Resolve-DnsName -Name "test.${config.privateZoneName}" -Type A -DnsOnly

# Check DNS server forwarder configuration
Get-DnsServerForwarder

# Flush DNS cache on client
Clear-DnsClientCache
`;
}

const GENERATORS = {
  bicep: generateBicep,
  powershell: generatePowerShell,
  azcli: generateAzCli,
  onprem: generateOnPremDns,
};

export default function ConfigGenerator({ config }) {
  const [activeFormat, setActiveFormat] = useState('bicep');
  const [copied, setCopied] = useState(false);

  const code = GENERATORS[activeFormat](config);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = code;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    const format = FORMATS.find(f => f.id === activeFormat);
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hybrid-dns${format.ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass rounded-2xl p-6 animate-slide-up">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold text-white">Configuration Generator</h2>
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              copied
                ? 'bg-green-600 text-white'
                : 'bg-white/5 text-gray-400 hover:text-white'
            }`}
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </button>
          <button
            onClick={handleDownload}
            className="px-3 py-1.5 rounded-lg text-xs font-medium bg-white/5 text-gray-400 hover:text-white transition-all"
          >
            ⬇ Download
          </button>
        </div>
      </div>

      {/* Format tabs */}
      <div className="flex gap-1 mb-4 bg-white/5 rounded-xl p-1">
        {FORMATS.map(format => (
          <button
            key={format.id}
            onClick={() => setActiveFormat(format.id)}
            className={`flex-1 px-3 py-2 rounded-lg text-xs font-medium transition-all ${
              activeFormat === format.id
                ? 'bg-azure-600 text-white shadow-lg'
                : 'text-gray-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <span className="mr-1">{format.icon}</span>
            {format.label}
          </button>
        ))}
      </div>

      {/* Code output */}
      <div className="relative">
        <pre className="bg-black/40 rounded-xl p-4 overflow-x-auto text-sm leading-relaxed border border-white/5 max-h-[600px] overflow-y-auto">
          <code className="text-gray-300 whitespace-pre">{code}</code>
        </pre>
      </div>

      {/* Info banner */}
      <div className="mt-4 p-3 rounded-xl bg-azure-900/20 border border-azure-700/30 text-xs text-azure-300">
        💡 <strong>Tip:</strong> Update the configuration panel on the left to customize values. 
        All generated scripts will automatically reflect your settings.
        {activeFormat === 'onprem' && (
          <span className="block mt-1">
            🏢 Run these commands on your on-premises Windows DNS Server (Domain Controller).
          </span>
        )}
      </div>
    </div>
  );
}
